import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar";
import LoadingPage from "./components/loading";
import SideBar from "./components/sidebar";
import { Providers } from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {/* <LoadingPage /> */}
          <NavBar />
          <div className="flex mt-16 w-full overflow-x-hidden mr-2">
            <div className="h-full mb-20">
              <SideBar />
            </div>
            <div className="p-2 pt-4  md:p-8 w-full">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
